version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      PORT: 8000  
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
